export type LlmOption = {
  rank: number;
  model: string;
  developer: string;
  popularityTier: "Very High" | "High" | "Medium" | "Low" | "Niche";
  mainDriver: string;
};

export const LLM_CATALOG: LlmOption[] = [
  { rank: 1, model: "GPT 5.2", developer: "OpenAI", popularityTier: "Very High", mainDriver: "ChatGPT flagship" },
  { rank: 2, model: "GPT-5", developer: "OpenAI", popularityTier: "Very High", mainDriver: "ChatGPT flagship" },
  { rank: 3, model: "GPT-4.5", developer: "OpenAI", popularityTier: "Very High", mainDriver: "ChatGPT flagship" },
  { rank: 4, model: "GPT-4", developer: "OpenAI", popularityTier: "Very High", mainDriver: "ChatGPT flagship" },
  { rank: 5, model: "Gemini 3", developer: "Google DeepMind", popularityTier: "Very High", mainDriver: "Gemini consumer app" },
  { rank: 6, model: "Gemini 2.5", developer: "Google DeepMind", popularityTier: "High", mainDriver: "Gemini consumer app" },
  { rank: 7, model: "Gemini 2.0", developer: "Google DeepMind", popularityTier: "High", mainDriver: "Gemini consumer app" },
  { rank: 8, model: "Claude Opus 4.6", developer: "Anthropic", popularityTier: "High", mainDriver: "Claude chatbot/enterprise" },
  { rank: 9, model: "Qwen3-Max-Thinking", developer: "Alibaba Cloud", popularityTier: "High", mainDriver: "Top open downloads + CN app" },
  { rank: 10, model: "Claude Opus 4.5", developer: "Anthropic", popularityTier: "High", mainDriver: "Claude chatbot/enterprise" },
  { rank: 11, model: "Gemini 1.5", developer: "Google DeepMind", popularityTier: "High", mainDriver: "Gemini consumer app" },
  { rank: 12, model: "Llama 4", developer: "Meta", popularityTier: "High", mainDriver: "Top open downloads" },
  { rank: 13, model: "Qwen3", developer: "Alibaba Cloud", popularityTier: "High", mainDriver: "Top open downloads + CN app" },
  { rank: 14, model: "Claude Sonnet 4.5", developer: "Anthropic", popularityTier: "High", mainDriver: "Claude chatbot/enterprise" },
  { rank: 15, model: "GPT-3", developer: "OpenAI", popularityTier: "High", mainDriver: "Historic + widely used API" },
  { rank: 16, model: "Gemini Ultra", developer: "Google DeepMind", popularityTier: "High", mainDriver: "Gemini consumer app" },
  { rank: 17, model: "Llama 3.1", developer: "Meta", popularityTier: "High", mainDriver: "Top open downloads" },
  { rank: 18, model: "Qwen2.5", developer: "Alibaba", popularityTier: "High", mainDriver: "Top open downloads + CN app" },
  { rank: 19, model: "Claude 4.1", developer: "Anthropic", popularityTier: "High", mainDriver: "Claude chatbot/enterprise" },
  { rank: 20, model: "DeepSeek-R1", developer: "DeepSeek", popularityTier: "High", mainDriver: "Open models + CN adoption" },
  { rank: 21, model: "OpenAI o3 and o4-mini", developer: "OpenAI", popularityTier: "High", mainDriver: "Reasoning models" },
  { rank: 22, model: "Claude 4", developer: "Anthropic", popularityTier: "High", mainDriver: "Claude chatbot/enterprise" },
  { rank: 23, model: "DeepSeek-V3.1", developer: "DeepSeek", popularityTier: "High", mainDriver: "Open models + CN adoption" },
  { rank: 24, model: "Gemini 1.0", developer: "Google DeepMind", popularityTier: "High", mainDriver: "Gemini consumer app" },
  { rank: 25, model: "Llama 2", developer: "Meta", popularityTier: "High", mainDriver: "Top open downloads" },
  { rank: 26, model: "OpenAI o1", developer: "OpenAI", popularityTier: "High", mainDriver: "Reasoning model" },
  { rank: 27, model: "Qwen2", developer: "Alibaba Cloud", popularityTier: "High", mainDriver: "Top open downloads + CN app" },
  { rank: 28, model: "Claude 3.7", developer: "Anthropic", popularityTier: "High", mainDriver: "Claude chatbot/enterprise" },
  { rank: 29, model: "DeepSeek-V3", developer: "DeepSeek", popularityTier: "High", mainDriver: "Open models + CN adoption" },
  { rank: 30, model: "Claude 3.5", developer: "Anthropic", popularityTier: "High", mainDriver: "Claude chatbot/enterprise" },
  { rank: 31, model: "Llama", developer: "Meta", popularityTier: "High", mainDriver: "Top open downloads" },
  { rank: 32, model: "BERT", developer: "Google", popularityTier: "High", mainDriver: "Academic/industry classic" },
  { rank: 33, model: "DeepSeek-V2", developer: "DeepSeek", popularityTier: "High", mainDriver: "Open models + CN adoption" },
  { rank: 34, model: "GPT-5.3-Codex", developer: "OpenAI", popularityTier: "High", mainDriver: "Coding assistant" },
  { rank: 35, model: "Claude 3", developer: "Anthropic", popularityTier: "Medium", mainDriver: "Claude chatbot/enterprise" },
  { rank: 36, model: "DeepSeek-V3.2-Exp", developer: "DeepSeek", popularityTier: "Medium", mainDriver: "Open models + CN adoption" },
  { rank: 37, model: "Mistral Large", developer: "Mistral AI", popularityTier: "Medium", mainDriver: "Open weights (dev community)" },
  { rank: 38, model: "GPT-2", developer: "OpenAI", popularityTier: "Medium", mainDriver: "Historic, widely referenced" },
  { rank: 39, model: "Grok 4", developer: "xAI", popularityTier: "Medium", mainDriver: "Grok / X integration" },
  { rank: 40, model: "Mixtral 8x22B", developer: "Mistral AI", popularityTier: "Medium", mainDriver: "Open weights (dev community)" },
  { rank: 41, model: "Grok 3", developer: "xAI", popularityTier: "Medium", mainDriver: "Grok / X integration" },
  { rank: 42, model: "Mixtral 8x7B", developer: "Mistral AI", popularityTier: "Medium", mainDriver: "Open weights (dev community)" },
  { rank: 43, model: "Grok-2", developer: "xAI", popularityTier: "Medium", mainDriver: "Grok / X integration" },
  { rank: 44, model: "Pixtral", developer: "Mistral AI", popularityTier: "Medium", mainDriver: "Open weights (dev community)" },
  { rank: 45, model: "Claude 2.1", developer: "Anthropic", popularityTier: "Medium", mainDriver: "Claude chatbot/enterprise" },
  { rank: 46, model: "DeepSeek-LLM", developer: "DeepSeek", popularityTier: "Medium", mainDriver: "Open models + CN adoption" },
  { rank: 47, model: "Mistral 7B", developer: "Mistral AI", popularityTier: "Medium", mainDriver: "Open weights (dev community)" },
  { rank: 48, model: "Grok 1", developer: "xAI", popularityTier: "Medium", mainDriver: "Grok / X integration" },
  { rank: 49, model: "Phi-4", developer: "Microsoft", popularityTier: "Medium", mainDriver: "Small open model" },
  { rank: 50, model: "Claude 2", developer: "Anthropic", popularityTier: "Medium", mainDriver: "Claude chatbot/enterprise" },
  { rank: 51, model: "GPT-OSS", developer: "OpenAI", popularityTier: "Medium", mainDriver: "Open weights" },
  { rank: 52, model: "Gemma", developer: "Google DeepMind", popularityTier: "Medium", mainDriver: "Open weights" },
  { rank: 53, model: "Phi-3", developer: "Microsoft", popularityTier: "Medium", mainDriver: "Small open model" },
  { rank: 54, model: "Phi-2", developer: "Microsoft", popularityTier: "Medium", mainDriver: "Small open model" },
  { rank: 55, model: "T5", developer: "Google", popularityTier: "Medium", mainDriver: "Academic/industry classic" },
  { rank: 56, model: "Claude", developer: "Anthropic", popularityTier: "Medium", mainDriver: "Claude chatbot/enterprise" },
  { rank: 57, model: "DBRX", developer: "Databricks", popularityTier: "Medium", mainDriver: "Open weights" },
  { rank: 58, model: "GLM-5", developer: "Zhipu AI", popularityTier: "Medium", mainDriver: "CN open-source (Zhipu)" },
  { rank: 59, model: "Nemotron-4", developer: "Nvidia", popularityTier: "Medium", mainDriver: "Open weights" },
  { rank: 60, model: "Falcon", developer: "Technology Innovation Institute", popularityTier: "Low", mainDriver: "Open weights" },
  { rank: 61, model: "GLM-4.7", developer: "Zhipu AI", popularityTier: "Low", mainDriver: "CN open-source (Zhipu)" },
  { rank: 62, model: "BLOOM", developer: "Hugging Face / BigScience", popularityTier: "Low", mainDriver: "Open weights" },
  { rank: 63, model: "GLM-4.6", developer: "Zhipu AI", popularityTier: "Low", mainDriver: "CN open-source (Zhipu)" },
  { rank: 64, model: "Ernie 3.0 Titan", developer: "Baidu", popularityTier: "Low", mainDriver: "Regional (Baidu/Ernie)" },
  { rank: 65, model: "GLM-4.5", developer: "Zhipu AI", popularityTier: "Low", mainDriver: "CN open-source (Zhipu)" },
  { rank: 66, model: "OPT (Open Pretrained Transformer)", developer: "Meta", popularityTier: "Low", mainDriver: "Open weights" },
  { rank: 67, model: "YandexGPT 5.1 Pro", developer: "Yandex", popularityTier: "Low", mainDriver: "Regional (Yandex/Alice)" },
  { rank: 68, model: "Chameleon", developer: "Meta", popularityTier: "Low", mainDriver: "Open weights (multimodal)" },
  { rank: 69, model: "GPT-NeoX", developer: "EleutherAI", popularityTier: "Low", mainDriver: "Open weights" },
  { rank: 70, model: "YandexGPT 5 Lite Pretrain and Pro", developer: "Yandex", popularityTier: "Low", mainDriver: "Regional (Yandex/Alice)" },
  { rank: 71, model: "GPT-J", developer: "EleutherAI", popularityTier: "Low", mainDriver: "Open weights" },
  { rank: 72, model: "YandexGPT 4 Lite and Pro", developer: "Yandex", popularityTier: "Low", mainDriver: "Regional (Yandex/Alice)" },
  { rank: 73, model: "YandexGPT 5 Lite Instruct", developer: "Yandex", popularityTier: "Low", mainDriver: "Regional (Yandex/Alice)" },
  { rank: 74, model: "YandexGPT 3 Pro", developer: "Yandex", popularityTier: "Low", mainDriver: "Regional (Yandex/Alice)" },
  { rank: 75, model: "GPT-Neo", developer: "EleutherAI", popularityTier: "Low", mainDriver: "Open weights" },
  { rank: 76, model: "PaLM 2 (Pathways Language Model 2)", developer: "Google", popularityTier: "Low", mainDriver: "Research (Google)" },
  { rank: 77, model: "YandexGPT 3 Lite", developer: "Yandex", popularityTier: "Low", mainDriver: "Regional (Yandex/Alice)" },
  { rank: 78, model: "YandexGPT 2", developer: "Yandex", popularityTier: "Low", mainDriver: "Regional (Yandex/Alice)" },
  { rank: 79, model: "Amazon Nova", developer: "Amazon", popularityTier: "Low", mainDriver: "Proprietary (Amazon)" },
  { rank: 80, model: "Chinchilla", developer: "DeepMind", popularityTier: "Low", mainDriver: "Academic scaling-law classic" },
  { rank: 81, model: "GPT-1", developer: "OpenAI", popularityTier: "Low", mainDriver: "Historic" },
  { rank: 82, model: "Jurassic-2", developer: "AI21 Labs", popularityTier: "Low", mainDriver: "Commercial (AI21)" },
  { rank: 83, model: "Kimi K2.5", developer: "Moonshot AI", popularityTier: "Low", mainDriver: "Regional (Moonshot/Kimi)" },
  { rank: 84, model: "OpenAssistant", developer: "LAION", popularityTier: "Low", mainDriver: "Open weights" },
  { rank: 85, model: "PaLM (Pathways Language Model)", developer: "Google", popularityTier: "Low", mainDriver: "Research (Google)" },
  { rank: 86, model: "XLNet", developer: "Google", popularityTier: "Low", mainDriver: "Academic/industry classic" },
  { rank: 87, model: "YandexGPT", developer: "Yandex", popularityTier: "Low", mainDriver: "Regional (Yandex/Alice)" },
  { rank: 88, model: "LaMDA (Language Models for Dialog Applications)", developer: "Google", popularityTier: "Niche", mainDriver: "Research (Google)" },
  { rank: 89, model: "Granite Code Models", developer: "IBM", popularityTier: "Niche", mainDriver: "Enterprise (IBM)" },
  { rank: 90, model: "AlexaTM (Teacher Models)", developer: "Amazon", popularityTier: "Niche", mainDriver: "Research/proprietary" },
  { rank: 91, model: "Alice AI LLM 1.0", developer: "Yandex", popularityTier: "Niche", mainDriver: "Regional (Yandex/Alice)" },
  { rank: 92, model: "GLaM (Generalist Language Model)", developer: "Google", popularityTier: "Niche", mainDriver: "Research (Google)" },
  { rank: 93, model: "Gopher", developer: "DeepMind", popularityTier: "Niche", mainDriver: "Research (DeepMind)" },
  { rank: 94, model: "Granite 13b", developer: "IBM", popularityTier: "Niche", mainDriver: "Enterprise (IBM)" },
  { rank: 95, model: "Megatron-Turing NLG", developer: "Microsoft and Nvidia", popularityTier: "Niche", mainDriver: "Research/proprietary" },
  { rank: 96, model: "Minerva", developer: "Google", popularityTier: "Niche", mainDriver: "Research (Google)" },
  { rank: 97, model: "MiniMax-Text-01", developer: "MiniMax", popularityTier: "Niche", mainDriver: "Regional (MiniMax)" },
  { rank: 98, model: "PanGu-Sigma", developer: "Huawei", popularityTier: "Niche", mainDriver: "Research/proprietary" },
  { rank: 99, model: "YaLM 100B", developer: "Yandex", popularityTier: "Niche", mainDriver: "Regional (Yandex/Alice)" },
  { rank: 100, model: "BloombergGPT", developer: "Bloomberg", popularityTier: "Niche", mainDriver: "Domain-specific (finance)" },
  { rank: 101, model: "Cerebras-GPT", developer: "Cerebras", popularityTier: "Niche", mainDriver: "Open weights" },
  { rank: 102, model: "Galactica", developer: "Meta", popularityTier: "Niche", mainDriver: "Withdrawn research model" },
  { rank: 103, model: "Apertus", developer: "ETH Zurich / EPFL", popularityTier: "Niche", mainDriver: "Research/open (EU)" },
  { rank: 104, model: "Fugaku-LLM", developer: "Fujitsu / Tokyo Institute of Technology / others", popularityTier: "Niche", mainDriver: "Research (HPC)" },
  { rank: 105, model: "Sarvam 1", developer: "Sarvam AI", popularityTier: "Niche", mainDriver: "Regional (India)" },
  { rank: 106, model: "Sarvam-M", developer: "Sarvam AI", popularityTier: "Niche", mainDriver: "Regional (India)" },
  { rank: 107, model: "Sarvam-2B", developer: "Sarvam AI", popularityTier: "Niche", mainDriver: "Regional (India)" },
  { rank: 108, model: "Sovereign LLM", developer: "Sarvam AI", popularityTier: "Niche", mainDriver: "Regional (India)" }
];
